version: "3"

services:
  travel-front-service:
    container_name: travel-front-service
    build: 
      context: .
      dockerfile: Dockerfile.dist
    ports:
      - 1000:8080
    restart: always
    networks:
      - travel-network

networks:
  travel-network:
    external: true
