services:
  travel-front-service:
    container_name: travel-front-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 1000:3000
    working_dir: /app
    command: npm run start
    networks:
      - travel-network

networks:
  travel-network:
    external: true
