version: '3'


services:
  project-t:
    container_name: project-t
    build: .
    ports:
      - 80:8080
    restart: always
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true